repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^docs/
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
- repo: local
  hooks:
  - id: rubocop
    name: rubocop
    entry: bundle exec rubocop --auto-correct
    language: system
    types: [ruby]
    pass_filenames: false
  - id: rspec
    name: rspec
    entry: bundle exec rspec
    language: system
    types: [ruby]
    pass_filenames: false
  - id: reek
    name: reek
    entry: bundle exec reek
    language: system
    types: [ruby]
    pass_filenames: false